version: "3.8"
services:
  client:
    container_name: "perntodo-client-compose"  
    build: ./client/
    stdin_open: true
    ports:
      - 4002:4002
    depends_on:
      - server

  server:
    container_name: "perntodo-server-compose"
    build: ./server/
    ports:
      - "4003:4003"
  pg:
    image: "postgres:latest"
    container_name: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - ./pg/db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "perntodo"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "1234567?"
      POSTGRES_HOST_AUTH_METHOD: "trust"