version: "3"
services:
  react_client:
    container_name: "aykutmyl/perntodo-client"  
    build: ./client/
    stdin_open: true
    ports:
      - 3000:3000
    depends_on:
      - aykutmyl/perntodo-server

  node_backend:
    container_name: "aykutmyl/perntodo-server"
    build: ./server/
    ports:
      - "3001:3001"
  pg:
    image: "postgres:latest"
    container_name: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - ./pg/db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "perntodo"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "1234567?"
      POSTGRES_HOST_AUTH_METHOD: "trust"